### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by abr4xas** [mikeal/planet#4]
Hi there!!

```
events.js:71
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: listen EACCES
    at errnoException (net.js:770:11)
    at Server._listen2 (net.js:893:19)
    at listen (net.js:937:10)
    at Server.listen (net.js:986:5)
    at /home/abr4xas/Proyectos/planet/main.js:239:6
    at /home/abr4xas/Proyectos/planet/main.js:162:9
    at readFiles (/home/abr4xas/Proyectos/planet/main.js:87:27)
    at /home/abr4xas/Proyectos/planet/main.js:123:7
    at Object.oncomplete (fs.js:297:15)

```

**Comment by abr4xas** [comment]
Hi there, 

For some reason when running using sudo does not return any error and ran without problems.
Anyway, if you can validate the reason for the error and how to fix described above would be excellent.
Thanks

**Comment by danmactough** [comment]
@abr4xas `npm start` or `node server.js` is configured to listen on port 80. You can't listen on a privileged port unless you're a superuser. That's why running with sudo worked. If you're debugging, try using `node debug.js` instead, which will listen on port 8000 not 80.
